# Generated by Django 4.0.10 on 2023-07-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seetherstore', '0006_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='child_category',
            field=models.BooleanField(default=False),
        ),
    ]
