# Generated by Django 4.0.10 on 2023-05-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_plaintext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaintext',
            old_name='introduction',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
