# Generated by Django 4.0.10 on 2023-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_mailmessage_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('send_it', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to='blog.subscribers')),
            ],
            options={
                'verbose_name': 'Emails to send',
                'verbose_name_plural': 'Emails to send',
            },
        ),
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
