# Generated by Django 4.0.10 on 2023-06-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_mailmessage_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='users',
        ),
    ]
